In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 


#import matplotlib as plt 
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
data = pd.read_csv('https://datautmexample.s3.amazonaws.com/COVID-19_Case_Surveillance_Public_Use_Data.csv')

MemoryError: Unable to allocate 64.1 MiB for an array with shape (8405079,) and data type object

In [4]:
data

,cdc_report_dt,pos_spec_dt,onset_dt,current_status,sex,age_group,Race and ethnicity (combined),hosp_yn,icu_yn,death_yn,medcond_yn
0,2020/11/10,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,Unknown,No,No
1,2020/11/14,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
2,2020/11/19,2020/11/10,2020/11/09,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,No
3,2020/11/14,2020/11/10,NaN,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",Missing,Missing,No,Missing
4,2020/11/13,2020/11/10,2020/11/10,Laboratory-confirmed case,Male,10 - 19 Years,"Black, Non-Hispanic",No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...
8405074,2020/10/22,NaN,NaN,Probable Case,Missing,30 - 39 Years,Unknown,No,Unknown,No,Missing
8405075,2020/10/25,NaN,NaN,Laboratory-confirmed case,Missing,30 - 39 Years,Unknown,Missing,Missing,Missing,Missing
8405076,2020/07/18,NaN,NaN,Laboratory-confirmed case,Missing,30 - 39 Years,Unknown,Missing,Missing,Missing,Missing
8405077,2020/11/19,NaN,NaN,Laboratory-confirmed case,Missing,30 - 39 Years,Unknown,Missing,Missing,Missing,Missing
8405078,2020/11/03,NaN,NaN,Laboratory-confirmed case,Missing,30 - 39 Years,Unknown,No,Unknown,No,Missing

In [5]:
relation = data[['cdc_report_dt','pos_spec_dt','onset_dt','current_status']]

In [6]:
relation

        cdc_report_dt pos_spec_dt    onset_dt             current_status
0          2020/11/10  2020/11/10         NaN  Laboratory-confirmed case
1          2020/11/14  2020/11/10  2020/11/10  Laboratory-confirmed case
2          2020/11/19  2020/11/10  2020/11/09  Laboratory-confirmed case
3          2020/11/14  2020/11/10         NaN  Laboratory-confirmed case
4          2020/11/13  2020/11/10  2020/11/10  Laboratory-confirmed case
...               ...         ...         ...                        ...
8405074    2020/10/22         NaN         NaN              Probable Case
8405075    2020/10/25         NaN         NaN  Laboratory-confirmed case
8405076    2020/07/18         NaN         NaN  Laboratory-confirmed case
8405077    2020/11/19         NaN         NaN  Laboratory-confirmed case
8405078    2020/11/03         NaN         NaN  Laboratory-confirmed case

[8405079 rows x 4 columns]

In [7]:
data.columns

Index(['cdc_report_dt', 'pos_spec_dt', 'onset_dt', 'current_status', 'sex',
       'age_group', 'Race and ethnicity (combined)', 'hosp_yn', 'icu_yn',
       'death_yn', 'medcond_yn'],
      dtype='object')

In [8]:
relation.head(10)

  cdc_report_dt pos_spec_dt    onset_dt             current_status
0    2020/11/10  2020/11/10         NaN  Laboratory-confirmed case
1    2020/11/14  2020/11/10  2020/11/10  Laboratory-confirmed case
2    2020/11/19  2020/11/10  2020/11/09  Laboratory-confirmed case
3    2020/11/14  2020/11/10         NaN  Laboratory-confirmed case
4    2020/11/13  2020/11/10  2020/11/10  Laboratory-confirmed case
5    2020/11/17  2020/11/10  2020/11/08  Laboratory-confirmed case
6    2020/11/14  2020/11/10         NaN  Laboratory-confirmed case
7    2020/11/10  2020/11/10         NaN  Laboratory-confirmed case
8    2020/11/10  2020/11/10         NaN  Laboratory-confirmed case
9    2020/11/17  2020/11/10         NaN  Laboratory-confirmed case

In [17]:
sns.pairplot(relation, kind='reg')
plt.show()

IndexError: index -1 is out of bounds for axis 0 with size 0

In [23]:
sns.distplot(data.4)

SyntaxError: invalid syntax (<ipython-input-23-3a987a868322>, line 1)

In [20]:
data.describe()

,cdc_report_dt,pos_spec_dt,onset_dt,current_status,sex,age_group,Race and ethnicity (combined),hosp_yn,icu_yn,death_yn,medcond_yn
count,8405079,2870789,4395957,8405079,8405061,8404990,8405072,8405079,8405079,8405079,8405079
unique,321,313,338,2,5,10,9,4,4,4,4
top,2020/06/24,2020/11/09,2020/11/02,Laboratory-confirmed case,Female,20 - 29 Years,Unknown,No,Missing,No,Missing
freq,155857,50595,49527,7910118,4340898,1635264,2781176,3502556,6178281,3690813,6063390

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8405079 entries, 0 to 8405078
Data columns (total 11 columns):
 #   Column                         Dtype
---  ------                         -----
 0   cdc_report_dt                  object
 1   pos_spec_dt                    object
 2   onset_dt                       object
 3   current_status                 object
 4   sex                            object
 5   age_group                      object
 6   Race and ethnicity (combined)  object
 7   hosp_yn                        object
 8   icu_yn                         object
 9   death_yn                       object
 10  medcond_yn                     object
dtypes: object(11)
memory usage: 705.4+ MB

In [25]:
data.columns

Index(['cdc_report_dt', 'pos_spec_dt', 'onset_dt', 'current_status', 'sex',
       'age_group', 'Race and ethnicity (combined)', 'hosp_yn', 'icu_yn',
       'death_yn', 'medcond_yn'],
      dtype='object')

In [26]:
data.index

RangeIndex(start=0, stop=8405079, step=1)